package bookings;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
//import bookings.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.03.21 16:23:19 // Generated by ComTest
 *
 */
public class ClientTest {



  // Generated by ComTest BEGIN
  /** testRegister117 */
  @Test
  public void testRegister117() {    // Client: 117
    Client kim = new Client(); 
    assertEquals("From: Client line: 119", 0, kim.getRegisterNro()); 
    kim.register(); 
    Client chen = new Client(); 
    chen.register(); 
    int n1 = kim.getRegisterNro(); 
    int n2 = chen.getRegisterNro(); 
    assertEquals("From: Client line: 125", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse211 */
  @Test
  public void testParse211() {    // Client: 211
    Client client = new Client(); 
    client.parse(" 1 |Mr.|Donald| Trump|||||||||||||||||||"); 
    assertEquals("From: Client line: 214", 1, client.getRegisterNro()); 
    client.register(); 
    int n = client.getRegisterNro(); 
    client.parse(""+(n+20)); 
    client.register(); 
    assertEquals("From: Client line: 221", n+20+1, client.getRegisterNro()); 
  } // Generated by ComTest END
}