package bookings;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
//import bookings.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.03.11 13:55:30 // Generated by ComTest
 *
 */
public class RoomTest {



  // Generated by ComTest BEGIN
  /** testRegister51 */
  @Test
  public void testRegister51() {    // Room: 51
    Room test = new Room(); 
    assertEquals("From: Room line: 53", 0, test.getRoomNo()); 
    test.register(); 
    Room test2 = new Room(); 
    test2.register(); 
    int n1 = test.getRoomNo(); 
    int n2 = test2.getRoomNo(); 
    assertEquals("From: Room line: 59", n2-1, n1); 
  } // Generated by ComTest END
}