package database;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static database.DataGenerate.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.03.11 15:49:38 // Generated by ComTest
 *
 */
public class DataGenerateTest {



  // Generated by ComTest BEGIN
  /** testGenerateBinary52 */
  @Test
  public void testGenerateBinary52() {    // DataGenerate: 52
    int test1 = generateBinary(); 
    assertEquals("From: DataGenerate line: 54", true, (test1 == 1 || test1 == 0)); 
  } // Generated by ComTest END
}