package bookings;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
//import bookings.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.03.22 17:13:43 // Generated by ComTest
 *
 */
public class CalendarViewTest {



  // Generated by ComTest BEGIN
  /** testGiveReservations40 */
  @Test
  public void testGiveReservations40() {    // CalendarView: 40
    CalendarView cv = new CalendarView(); 
    Client test1 = new Client(), test2 = new Client(), test3 = new Client(); 
    test1.register(); test2.register(); test3.register(); 
    int id1 = test1.getRegisterNro(); 
    int id2 = test2.getRegisterNro(); 
    Reservation res1 = new Reservation(id1); cv.add(res1); 
    Reservation res2 = new Reservation(id1); cv.add(res2); 
    Reservation res3 = new Reservation(id2); cv.add(res3); 
    Reservation res4 = new Reservation(id2); cv.add(res4); 
    Reservation res5 = new Reservation(id2); cv.add(res5); 
    List<Reservation> found; 
    found = cv.giveReservations(test3); 
    assertEquals("From: CalendarView line: 56", 0, found.size()); 
    found = cv.giveReservations(test1); 
    assertEquals("From: CalendarView line: 58", 2, found.size()); 
    assertEquals("From: CalendarView line: 59", true, found.get(0) == res1); 
    assertEquals("From: CalendarView line: 60", true, found.get(1) == res2); 
    found = cv.giveReservations(test2); 
    assertEquals("From: CalendarView line: 62", 3, found.size()); 
    assertEquals("From: CalendarView line: 63", true, found.get(0) == res3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAdd84 
   * @throws HoldException when error
   */
  @Test
  public void testAdd84() throws HoldException {    // CalendarView: 84
    CalendarView clients = new CalendarView(); 
    Client ronald = new Client(), george = new Client(); 
    assertEquals("From: CalendarView line: 88", 0, clients.getClients()); 
    clients.add(ronald); assertEquals("From: CalendarView line: 89", 1, clients.getClients()); 
    clients.add(george); assertEquals("From: CalendarView line: 90", 2, clients.getClients()); 
    clients.add(ronald); assertEquals("From: CalendarView line: 91", 3, clients.getClients()); 
    assertEquals("From: CalendarView line: 92", ronald, clients.giveClient(0)); 
    assertEquals("From: CalendarView line: 93", george, clients.giveClient(1)); 
    assertEquals("From: CalendarView line: 94", ronald, clients.giveClient(2)); 
    assertEquals("From: CalendarView line: 95", false, clients.giveClient(1) == ronald); 
    assertEquals("From: CalendarView line: 96", true, clients.giveClient(1) == george); 
    try {
    assertEquals("From: CalendarView line: 97", ronald, clients.giveClient(3)); 
    fail("CalendarView: 97 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    clients.add(ronald); assertEquals("From: CalendarView line: 98", 4, clients.getClients()); 
    clients.add(ronald); assertEquals("From: CalendarView line: 99", 5, clients.getClients()); 
  } // Generated by ComTest END
}